spring.application.name=CineJunction

# Active Profile
spring.profiles.active=dev

# JWT Defaults
jwt.expiration=86400000

# Server
server.port=8080

# Jackson
spring.jackson.serialization.indent-output=true