# ===============================
# PostgreSQL Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/cinejunction
spring.datasource.username=postgres
spring.datasource.password=54712

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# PostgreSQL Driver
# ===============================
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JWT
# ===============================
jwt.secret=CineJunctionSuperSecretKeyForJwtAuthentication2026SecureKey123
# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE