# Application Name
spring.application.name=CineJunction

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/cinejunction
spring.datasource.username=postgres
spring.datasource.password=54712

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Port
server.port=8080

# JWT Configuration
jwt.secret=VGhpc0lzQUNpbmVKdW5jdGlvbkpXVFNlY3JldEtleUZvckRldmVsb3BtZW50MTIzNDU2Nzg5MA==
jwt.expiration=86400000