spring.application.name=CineJunction

# Active Profile
spring.profiles.active=dev

# JWT Defaults
jwt.expiration=86400000

# Server
server.port=8080

# Jackson
spring.jackson.serialization.indent-output=true

# TMDb
tmdb.api.key=90f501fa40d4dbe60af795330f8dfe48
tmdb.base-url=https://api.themoviedb.org/3